const searchModule={
  state:()=>({
    search:[
      {
        id:1,
        imgurl:require('../../assets/images/search1.jpg'),
        title:'<阿尔山童话世界冰雪温泉之旅>6天行程',
        price:'￥3600',
        slogan:'冰雪阿尔山欢乐过大年',
        route:'线路：南京-乌兰浩特-阿尔山-白狼村',
        guide:'探索者旅行俱乐部'
      },
      {
        id:2,
        imgurl:require('../../assets/images/search2.jpg'),
        title:'<海天佛国 普陀山祈福之旅>3天行程',
        price:'￥1280',
        slogan:'海天佛国，南海圣境',
        route:'线路：南京-朱家尖-普陀山-宁波',
        guide:'中国自驾游联盟南京站'
      },
      {
        id:3,
        imgurl:require('../../assets/images/search3.jpg'),
        title:'<玩转广西自驾桂林12日游>12天行程',
        price:'￥4680',
        slogan:'领略广西风光，体验中越边关风采',
        route:'线路：南京-桂林-凭祥-北海-阳朔',
        guide:'中国自驾游联盟南京站'
      },
      {
        id:4,
        imgurl:require('../../assets/images/search4.jpg'),
        title:'<黔东南深度名宿体验之旅>12天行程',
        price:'￥4580',
        slogan:'冰雪阿尔山欢乐过大年',
        route:'线路：南京-江西-黄果树-荔波-桂林',
        guide:'中国自驾游联盟南京站'
      }
    ]
  })
}
export default searchModule